# Generated by Django 4.2.4 on 2023-09-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_siteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
