# Generated by Django 4.2.4 on 2023-09-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='phone2',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='address1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='address2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
