# Generated by Django 4.2.4 on 2023-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_massage_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('use_for', models.CharField(max_length=300)),
                ('row_1', models.CharField(max_length=300)),
                ('row_2', models.CharField(max_length=300)),
                ('row_3', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
